version: '3.8'
services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sensor_app
    ports:
      - "8081:8080"
    environment:
      - MONGO_DB_URL=${MONGO_DB_URL}
    command: ["python", "sensor/main.py"]
    volumes:
      - E:\sensordetect:/app